### PR TITLE
Add Ubuntu 24.04 LTS (Noble Numbat) to Supported Operating Systems (Update installing.rst)

### PR DESCRIPTION
**Pull request by Minionguyjpro**
This adds the fresh and new Ubuntu LTS version to the supported list of operating systems. I must be honest that I didn't test it with 24.04 in an LXC container yet, but I am updating it right now and after that I will let y'all know whether it will work. But I am pretty sure it will.

### CODE REVIEW

**Comment by LordRalex** [comment]
It is not supported, because the 2.x releases do not push to their repos.

**Comment by nepcore** [comment]
Try a fresh install on a fresh system instead of a distro upgrade and you'll see that it's not quite that simple.  
It's much less about does PufferPanel function on that system, but rather about if the install instructions will work, which depends on us having set up a package repo for that specific Ubuntu version and published a release into it, as we have not yet released a new version since the new Ubuntu LTS release we do not yet have any packages published for that and the unsupported version approach is the only way to get the install to work. (Do note that a new PufferPanel version also doesn't have any guarantee to get released for that new Ubuntu version either, but without that it'd be highly unlikely to see proper support for it)

**Comment by Minionguyjpro** [comment]
> It is not supported, because the 2.x releases do not push to their repos.

Wait wait wait, what do you mean exactly? It's not on the APT repositories yet?

EDIT: I understand, we still need an optimized package in the new noble APT repos.

**Comment by Minionguyjpro** [comment]
I am still upgrading in case. I'll probably have to change or keep the pufferpanel APT repo to use jammy instead of noble but it should work even though it's not in the proper support yet (I think it's unlikely that 24.04 will never be supported and I guess it may be in a next release, right?).

**Comment by Minionguyjpro** [comment]
Hmmm, @LordRalex and @nepcore. Even though y'all said that it's not supported it seems like it is available as an ``ubuntu/noble`` package here:
PufferPanel on PackageCloud.io

**Comment by Minionguyjpro** [comment]
And this seems to work too:
APT

**Comment by LordRalex** [comment]
Maybe I just uploaded it when it wasn't fully released.... well, that's a little different....

**Comment by Minionguyjpro** [comment]
> Maybe I just uploaded it when it wasn't fully released.... well, that's a little different....

Or it's automatically handled by PackageCloud? I'm not sure, it seems like a site that could do it <-- Nevermind this, otherwise it would have done it for older releases too probably >. It seems like only 2.7 is for noble yet.

**Comment by Minionguyjpro** [comment]
Oh I guess it's out, since I see that the branches on the ``pufferpanel`` also got updated to v3 and things. Anyway, I guess it's time to make another PR but for Debian 12 (bookworm) :+1:.

**Pull request merged**
